version: '3'

services:
    communication:
        build: ./Communication/
        #image: name/tag
        ports:
            - 1100:1100
        restart: always
    driverrider:
        build: ./DriverRider/
        #image: name/tag
        restart: always
        depends_on:
            - communication
    rating:
        build: ./Rating/
        #image: name/tag
        restart: always
    database:
        image: mysql:latest
        ports:
            - "33061:3306"
        volumes:
            - ./init.sql:/data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
    nginx:
        build: ./nginx/
        ports:
            - 8080:80
        depends_on:
            - rating
            - communication
            - driverrider
